"""Add daily_cash_balances table for StmtFunds data

Revision ID: 5054502cdf05
Revises: c2d3e4f5g6h7
Create Date: 2026-01-12 09:22:20.404395

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5054502cdf05"
down_revision: str | None = "c2d3e4f5g6h7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_cash_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("balance", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("activity", sa.String(length=255), nullable=True),
        sa.Column("broker_source_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["broker_source_id"], ["broker_data_sources.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "date", "currency", name="uq_daily_cash_balance"),
    )
    op.create_index(
        "idx_cash_balance_account_currency",
        "daily_cash_balances",
        ["account_id", "currency"],
        unique=False,
    )
    op.create_index(
        "idx_cash_balance_account_date", "daily_cash_balances", ["account_id", "date"], unique=False
    )
    op.create_index(op.f("ix_daily_cash_balances_id"), "daily_cash_balances", ["id"], unique=False)
    op.create_index(op.f("ix_asset_prices_id"), "asset_prices", ["id"], unique=False)
    op.create_index(op.f("ix_broker_data_sources_id"), "broker_data_sources", ["id"], unique=False)
    op.drop_index(op.f("idx_corporate_actions_date"), table_name="corporate_actions")
    op.drop_index(op.f("idx_corporate_actions_new_asset"), table_name="corporate_actions")
    op.drop_index(op.f("idx_corporate_actions_old_asset"), table_name="corporate_actions")
    op.drop_index(op.f("idx_corporate_actions_type"), table_name="corporate_actions")
    op.create_index(op.f("ix_user_preferences_id"), "user_preferences", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_preferences_id"), table_name="user_preferences")
    op.create_index(
        op.f("idx_corporate_actions_type"), "corporate_actions", ["action_type"], unique=False
    )
    op.create_index(
        op.f("idx_corporate_actions_old_asset"), "corporate_actions", ["old_asset_id"], unique=False
    )
    op.create_index(
        op.f("idx_corporate_actions_new_asset"), "corporate_actions", ["new_asset_id"], unique=False
    )
    op.create_index(
        op.f("idx_corporate_actions_date"), "corporate_actions", ["effective_date"], unique=False
    )
    op.drop_index(op.f("ix_broker_data_sources_id"), table_name="broker_data_sources")
    op.drop_index(op.f("ix_asset_prices_id"), table_name="asset_prices")
    op.drop_index(op.f("ix_daily_cash_balances_id"), table_name="daily_cash_balances")
    op.drop_index("idx_cash_balance_account_date", table_name="daily_cash_balances")
    op.drop_index("idx_cash_balance_account_currency", table_name="daily_cash_balances")
    op.drop_table("daily_cash_balances")
    # ### end Alembic commands ###
