"""Initial schema: entities, accounts, assets, holdings, holding_lots, transactions, exchange_rates, historical_snapshots

Revision ID: e9aca3dbb267
Revises:
Create Date: 2025-12-12 10:08:41.166822

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9aca3dbb267"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_class", sa.String(length=50), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("is_manual_valuation", sa.Boolean(), nullable=False),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("last_fetched_price", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_index("idx_assets_class", "assets", ["asset_class"], unique=False)
    op.create_index("idx_assets_symbol", "assets", ["symbol"], unique=False)
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_id"), "entities", ["id"], unique=False)
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_currency", sa.String(length=3), nullable=False),
        sa.Column("to_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_currency", "to_currency", "date", name="uq_exchange_rate"),
    )
    op.create_index(
        "idx_rates_currencies_date",
        "exchange_rates",
        ["from_currency", "to_currency", "date"],
        unique=False,
    )
    op.create_index(op.f("ix_exchange_rates_id"), "exchange_rates", ["id"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("institution", sa.String(length=100), nullable=True),
        sa.Column("account_type", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("account_number", sa.String(length=100), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_accounts_entity", "accounts", ["entity_id"], unique=False)
    op.create_index(op.f("ix_accounts_id"), "accounts", ["id"], unique=False)
    op.create_table(
        "historical_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("total_value_usd", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("total_value_ils", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "account_id", name="uq_snapshot_date_account"),
    )
    op.create_index("idx_snapshots_account", "historical_snapshots", ["account_id"], unique=False)
    op.create_index("idx_snapshots_date", "historical_snapshots", ["date"], unique=False)
    op.create_index(
        op.f("ix_historical_snapshots_id"), "historical_snapshots", ["id"], unique=False
    )
    op.create_table(
        "holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("strategy_horizon", sa.String(length=20), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "asset_id", name="uq_holding_account_asset"),
    )
    op.create_index("idx_holdings_account", "holdings", ["account_id"], unique=False)
    op.create_index("idx_holdings_active", "holdings", ["is_active"], unique=False)
    op.create_index("idx_holdings_asset", "holdings", ["asset_id"], unique=False)
    op.create_index(op.f("ix_holdings_id"), "holdings", ["id"], unique=False)
    op.create_table(
        "holding_lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("holding_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cost_per_unit", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("purchase_price_original", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("fees", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("remaining_quantity", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["holding_id"], ["holdings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_lots_closed", "holding_lots", ["is_closed"], unique=False)
    op.create_index("idx_lots_holding", "holding_lots", ["holding_id"], unique=False)
    op.create_index("idx_lots_purchase_date", "holding_lots", ["purchase_date"], unique=False)
    op.create_index(op.f("ix_holding_lots_id"), "holding_lots", ["id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("holding_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("price_per_unit", sa.Numeric(precision=15, scale=4), nullable=True),
        sa.Column("fees", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency_rate_to_usd_at_date", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["holding_id"], ["holdings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_transactions_date", "transactions", ["date"], unique=False)
    op.create_index("idx_transactions_holding", "transactions", ["holding_id"], unique=False)
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index("idx_transactions_holding", table_name="transactions")
    op.drop_index("idx_transactions_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_holding_lots_id"), table_name="holding_lots")
    op.drop_index("idx_lots_purchase_date", table_name="holding_lots")
    op.drop_index("idx_lots_holding", table_name="holding_lots")
    op.drop_index("idx_lots_closed", table_name="holding_lots")
    op.drop_table("holding_lots")
    op.drop_index(op.f("ix_holdings_id"), table_name="holdings")
    op.drop_index("idx_holdings_asset", table_name="holdings")
    op.drop_index("idx_holdings_active", table_name="holdings")
    op.drop_index("idx_holdings_account", table_name="holdings")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_historical_snapshots_id"), table_name="historical_snapshots")
    op.drop_index("idx_snapshots_date", table_name="historical_snapshots")
    op.drop_index("idx_snapshots_account", table_name="historical_snapshots")
    op.drop_table("historical_snapshots")
    op.drop_index(op.f("ix_accounts_id"), table_name="accounts")
    op.drop_index("idx_accounts_entity", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_exchange_rates_id"), table_name="exchange_rates")
    op.drop_index("idx_rates_currencies_date", table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index(op.f("ix_entities_id"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_index("idx_assets_symbol", table_name="assets")
    op.drop_index("idx_assets_class", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
